name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
        - '3.10'
        - '3.11'
        - '3.12'
        - '3.13'
        torch:
        - '2.2.0'

    name: Python ${{ matrix.python }}, Torch ${{ matrix.torch }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Install torch
      run: pip3 install --upgrade torch==${{ matrix.torch}}
    - name: Run Black
      run: black . --check
    - name: Run pyright
      uses: jakebailey/pyright-action@v2.0.1
    - name: Run pytest
      run: |
        export PYTHONPATH=$(pwd)
        pytest tests
